services:
  api:
    build: ./api
    networks:
      - backend_net
    scale: 2
    expose:
      - "5000"
    
  web: 
    image: busybox
    command: sleep infinity
    expose:
      - 1234
    networks:
      - frontend_net      
  
  nginx:
    image: nginx:1.21-alpine
    container_name: load_balancer
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_net
      - frontend_net

networks:
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  frontend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  
