services:
  api:
    build: ./api
    container_name: car_api
    networks:
      backend_net:
        ipv4_address: 172.28.0.10  # Controlled IP
    expose:
      - "5000"

  nginx:
    image: nginx:1.21-alpine
    container_name: load_balancer
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      backend_net:
        ipv4_address: 172.28.0.11

networks:
  backend_net:
    ipam:
      config:
        - subnet: 172.28.0.0/24
