services:
  nginx1:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chatnet
      - wrapper
  nginx2:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chatnet2
      - wrapper
  busybox:
    image: busybox
    command: dig nginx2 
    networks:
      - wrapper

networks:
  chatnet:
  chatnet2:
  wrapper: